// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_spashScreen_screen_init(void)
{
    ui_spashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_spashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_spashScreen, &ui_img_splashscreen_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_spashScreen, ui_event_spashScreen, LV_EVENT_ALL, NULL);

}
